language: python
branch:
  only:
  - gh-pages
  - master
script: python gen_sidebar.py
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
